# Generated by Django 6.0.3 on 2026-03-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=125)),
                ('last_name', models.CharField(max_length=125)),
                ('age', models.CharField(max_length=100)),
                ('monthly_salary', models.CharField(max_length=10000)),
            ],
        ),
    ]
